name: airen
version: 1.0.0+1
publish_to: none
description: airen water meter app.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hexcolor:
  logger: any
  flutter_flavor: any
  http: any
  flutter_svg: any
  google_fonts: any
  flutter_staggered_grid_view: any
  lazy_load_scrollview: any
  intl: any
  get_storage: any
  get: 4.6.1
  flutter_html:
  flutter_launcher_icons:
  device_preview:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter: 
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  assets:
    - assets/

