name: airen
version: 1.0.0+1
publish_to: none
description: airen water meter app.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  hexcolor:
  logger: any
  flutter_flavor: any
  http: any
  flutter_svg: any
  google_fonts: any
  flutter_staggered_grid_view: any
  lazy_load_scrollview: any
  intl: any
  get_storage: any
  get: 4.6.1
  flutter_html:
  flutter_launcher_icons:
  device_preview:
  eva_icons_flutter:
  otp_text_field: ^1.0.0
  flutter_otp_timer:
  otp_count_down: ^1.0.6
  google_sign_in:
  rename: ^2.0.1
  url_launcher:
  path_provider:
  open_file:
  pdf:
  file_picker:
  currency_text_input_formatter: ^2.1.1
  rounded_loading_button:
  image_picker: ^0.8.5
  image_cropper: ^1.3.0
  photo_manager:
  filesize: ^2.0.1
  sticky_grouped_list: ^2.1.0
  blue_thermal_printer: ^1.2.0
  app_settings: ^4.1.5
  flutter:
    sdk: flutter
  date_util: ^0.1.4

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/iconfix.png"

flutter: 
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
  assets:
    - assets/

